# Generated by Django 3.1.3 on 2020-12-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
